[package]
name = "ffmpeg_custom"
version = "0.1.0"
edition = "2021"


[dependencies]
c2pa = { version = "0.33.1", features = ["file_io", "add_thumbnails","openssl_sign" ] }
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.3.0"
serde_json = "1.0"
[lib]
crate-type = ["cdylib"]
